/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
    "integration": "react-1-OrCau0N-2owzPNQJ8bKHMC8tBr6jz9WPSJiYQf1Z72jY39ZixXnfe4VJbZ9m9Y-ds2jevR-fJ5sgAi1uXSFRSCybRp-JY36XW15gKYk7SG4bNIQAky3vAQ9-",
    "tt": "tt-1-JA-rY92BLqgoiSAW-C4eIGCK15iWbSHfDe2c-Dz9JTk=",
    "version": "2020-11-20"
}
  
export default ebconfig;